package com.rowery

import com.rowery.Fact;
import com.rowery.Engine;







//-------Question-------------------------
rule "qinit"
	when
	then
		Engine.Question("who");
end
rule "qtype"
	when
		(
			Fact(name("who"), val ==0);
			or 
			Fact(name("who"), val ==1);
		)
	then
		Engine.Question("type");
end

rule "qwhat"
	when
		Fact(name("type"), val ==6);
	then
		Engine.Question("what");
end


//___________M____________________________

rule "qheightmtb"
	when
		
		Fact(name("who"), val ==0);
		(
			Fact(name("type"),val==0);
			or
			Fact(name("type"),val==2);
			or
			Fact(name("type"),val==5);
			or
			Fact(name("what"),val==1);
		)
	then
		Engine.Question("height-m-mtb-g");
end

rule "qheightmi"
	when
		
		Fact(name("who"), val ==0);
		(
			Fact(name("type"),val==1);
			or
			Fact(name("type"),val==4);
			or
			Fact(name("what"),val==0);
		)
	then
		Engine.Question("height-m-mi-trek");
end
//___________K____________________________
rule "qheightmtbk"
	when
		
		Fact(name("who"), val ==1);
		(
			Fact(name("type"),val==0);
			or
			Fact(name("type"),val==2);
			or
			Fact(name("type"),val==5);
			or
			Fact(name("what"),val==1);
		)
	then
		Engine.Question("height-k-mtb-g");
end

rule "qheightmik"
	when
		
		Fact(name("who"), val ==1);
		(
			Fact(name("type"),val==1);
			or
			Fact(name("type"),val==4);
			or
			Fact(name("what"),val==0);
		)
	then
		Engine.Question("height-k-mi-trek");
end
//____________Dziecko_____________________
rule "qsidewheels"
	when
		Fact(name("who"), val == 2);
	then
		Engine.Question("sidewheels");
end

rule "qheight-d"
	when
		Fact(name("who"), val==2);
	then
		Engine.Question("height-d");
end
//-------Answer---------------------------
